// Package artifacts implements the content-addressed store for large
// execution evidence: stdout/stderr logs, diffs, and other material too
// large for a SQLite row (docs/ARCHITECTURE.md §10, ENGINEERING_STANDARDS.md
// §10, docs/SECURITY.md §14).
//
// Only compact metadata (protocol.ArtifactRef) is meant to reach durable
// control-plane records; the bytes live here, addressed by their digest so a
// later reader can prove the bytes have not changed.
package artifacts

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"github.com/olostan/DevCadience/internal/errs"
	"github.com/olostan/DevCadience/internal/ids"
	"github.com/olostan/DevCadience/internal/protocol"
)

// Store is a filesystem-backed, content-addressed artifact store.
//
// Layout: <root>/<projectID>/objects/<first-2-hex>/<full-hex-digest>. The
// project id is validated the same way controlplane validates it, so a
// project id can never be used to escape the store root; the digest is the
// only remaining path component and is generated by this package, never
// accepted from a caller.
type Store struct {
	root string
	ids  ids.Source
}

// NewStore returns a Store rooted at root, which must be an absolute path.
// The directory is created on first write, not here, so constructing a Store
// never has a filesystem side effect.
func NewStore(root string, idSource ids.Source) (*Store, error) {
	if root == "" || !filepath.IsAbs(root) {
		return nil, errs.New(errs.CategoryInvalidArgument, "artifacts: root must be an absolute path")
	}
	if idSource == nil {
		idSource = ids.NewULIDSource()
	}
	return &Store{root: filepath.Clean(root), ids: idSource}, nil
}

// PutInput describes one artifact write.
type PutInput struct {
	ProjectID string
	// Kind is a short producer-defined label, e.g. "stdout", "stderr",
	// "diff", "test-report". It becomes ArtifactRef.Kind.
	Kind string
	// MediaType is an optional MIME-ish type, e.g. "text/plain".
	MediaType string
	// Reader supplies the artifact bytes. Reading stops (without error) once
	// MaxBytes have been captured; Truncated on the result reports whether
	// more data existed. A limit of zero means unbounded.
	Reader   io.Reader
	MaxBytes int64
}

// PutResult is what a write produced.
type PutResult struct {
	Ref       protocol.ArtifactRef
	Truncated bool
}

// Put streams src to the store, computing its digest as it writes, and
// returns metadata suitable for a durable ArtifactRef.
//
// The write is atomic: bytes land in a temporary file in the same directory
// as the final object and are renamed into place only after the digest is
// known, so a reader can never observe a partial object, and a crash mid
// write leaves at most an orphaned temp file, never a corrupt named object.
// Because objects are content-addressed, writing the same bytes twice is a
// safe no-op: the second write's temp file is discarded once its digest
// matches an object that already exists.
func (s *Store) Put(ctx context.Context, in PutInput) (PutResult, error) {
	if err := validateProjectID(in.ProjectID); err != nil {
		return PutResult{}, err
	}
	if in.Kind == "" {
		return PutResult{}, errs.New(errs.CategoryInvalidArgument, "artifacts: kind is required")
	}
	if in.Reader == nil {
		return PutResult{}, errs.New(errs.CategoryInvalidArgument, "artifacts: reader is required")
	}
	if in.MaxBytes < 0 {
		return PutResult{}, errs.New(errs.CategoryInvalidArgument, "artifacts: max_bytes must not be negative")
	}

	objDir := filepath.Join(s.root, in.ProjectID, "objects")
	if err := os.MkdirAll(objDir, 0o700); err != nil {
		return PutResult{}, errs.Wrap(errs.CategoryInternal, err, "artifacts: create object directory")
	}
	tmp, err := os.CreateTemp(objDir, "tmp-*")
	if err != nil {
		return PutResult{}, errs.Wrap(errs.CategoryInternal, err, "artifacts: create temp file")
	}
	tmpPath := tmp.Name()
	removeTemp := true
	defer func() {
		if removeTemp {
			_ = os.Remove(tmpPath)
		}
	}()

	hasher := sha256.New()
	writer := io.MultiWriter(tmp, hasher)
	var written int64
	truncated := false
	reader := in.Reader
	limit := in.MaxBytes
	buf := make([]byte, 32*1024)
	for {
		if err := ctx.Err(); err != nil {
			_ = tmp.Close()
			return PutResult{}, errs.Wrap(errs.CategoryInternal, err, "artifacts: write cancelled")
		}
		n, rerr := reader.Read(buf)
		if n > 0 {
			chunk := buf[:n]
			if limit > 0 && written+int64(n) > limit {
				allowed := limit - written
				if allowed > 0 {
					if _, werr := writer.Write(chunk[:allowed]); werr != nil {
						_ = tmp.Close()
						return PutResult{}, errs.Wrap(errs.CategoryInternal, werr, "artifacts: write object")
					}
					written += allowed
				}
				truncated = true
				// Keep draining the source into the hash-less void so a
				// caller streaming from a live process is not blocked on a
				// full pipe; only the file and digest stop growing. This is
				// a bounded, cancellation-aware drain rather than
				// io.Copy(io.Discard, reader): an unbounded or still-live
				// reader (e.g. a process whose caller never closes its
				// pipe) must not be able to hang Put past ctx's deadline
				// just because the byte cap was already reached.
				if err := drainUntilCancelled(ctx, reader, buf); err != nil {
					_ = tmp.Close()
					return PutResult{}, errs.Wrap(errs.CategoryInternal, err, "artifacts: drain truncated source")
				}
				break
			}
			if _, werr := writer.Write(chunk); werr != nil {
				_ = tmp.Close()
				return PutResult{}, errs.Wrap(errs.CategoryInternal, werr, "artifacts: write object")
			}
			written += int64(n)
		}
		if rerr != nil {
			if rerr == io.EOF {
				break
			}
			_ = tmp.Close()
			return PutResult{}, errs.Wrap(errs.CategoryInternal, rerr, "artifacts: read source")
		}
	}
	if err := tmp.Sync(); err != nil {
		_ = tmp.Close()
		return PutResult{}, errs.Wrap(errs.CategoryInternal, err, "artifacts: sync object")
	}
	if err := tmp.Close(); err != nil {
		return PutResult{}, errs.Wrap(errs.CategoryInternal, err, "artifacts: close object")
	}

	digestHex := hex.EncodeToString(hasher.Sum(nil))
	digest := "sha256:" + digestHex
	finalPath := objectPath(s.root, in.ProjectID, digestHex)
	if err := os.MkdirAll(filepath.Dir(finalPath), 0o700); err != nil {
		return PutResult{}, errs.Wrap(errs.CategoryInternal, err, "artifacts: create shard directory")
	}
	if _, err := os.Stat(finalPath); err == nil {
		// Content-addressed collision with identical bytes: nothing to do.
	} else if !errors.Is(err, os.ErrNotExist) {
		return PutResult{}, errs.Wrap(errs.CategoryInternal, err, "artifacts: stat object")
	} else {
		if err := os.Chmod(tmpPath, 0o400); err != nil {
			return PutResult{}, errs.Wrap(errs.CategoryInternal, err, "artifacts: make object read-only")
		}
		if err := os.Rename(tmpPath, finalPath); err != nil {
			return PutResult{}, errs.Wrap(errs.CategoryInternal, err, "artifacts: publish object")
		}
		removeTemp = false
	}

	ref := protocol.ArtifactRef{
		ID:        s.ids.New("art"),
		Kind:      in.Kind,
		Locator:   locatorFor(in.ProjectID, digestHex),
		MediaType: in.MediaType,
		Digest:    digest,
		SizeBytes: written,
		Truncated: truncated,
	}
	if err := ref.Validate(); err != nil {
		return PutResult{}, err
	}
	return PutResult{Ref: ref, Truncated: truncated}, nil
}

// drainUntilCancelled reads and discards r until EOF, an error, or ctx is
// cancelled, whichever comes first. It exists so that once Put's byte cap is
// reached it can still let a live/unbounded source unblock (by consuming
// what it writes) without giving that source the power to hang Put forever:
// ctx.Err() is checked between reads, so a caller's deadline or cancellation
// still bounds the call.
func drainUntilCancelled(ctx context.Context, r io.Reader, buf []byte) error {
	for {
		if err := ctx.Err(); err != nil {
			return err
		}
		n, err := r.Read(buf)
		_ = n
		if err != nil {
			if err == io.EOF {
				return nil
			}
			return err
		}
	}
}

// PutBytes is a convenience wrapper for already-buffered content.
func (s *Store) PutBytes(ctx context.Context, projectID, kind, mediaType string, data []byte, maxBytes int64) (PutResult, error) {
	return s.Put(ctx, PutInput{
		ProjectID: projectID,
		Kind:      kind,
		MediaType: mediaType,
		Reader:    strings.NewReader(string(data)),
		MaxBytes:  maxBytes,
	})
}

// Open returns the artifact's bytes. It does not verify them against
// ref.Digest — it only resolves the locator and opens the underlying file;
// call Verify separately when the caller needs a digest check before or
// after reading.
//
// The locator is never taken from outside this package's own output: Open
// resolves strictly through ref.Locator, which Put generated, so a caller
// cannot pass an arbitrary path and reach outside the store root.
func (s *Store) Open(ref protocol.ArtifactRef) (io.ReadCloser, error) {
	path, err := s.resolveLocator(ref.Locator)
	if err != nil {
		return nil, err
	}
	f, err := os.Open(path)
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return nil, errs.Wrap(errs.CategoryNotFound, err, "artifact %s not found", ref.ID)
		}
		return nil, errs.Wrap(errs.CategoryInternal, err, "artifacts: open %s", ref.ID)
	}
	return f, nil
}

// Verify reads the artifact back and checks its bytes against ref.Digest.
func (s *Store) Verify(ref protocol.ArtifactRef) error {
	if ref.Digest == "" {
		return errs.New(errs.CategoryIntegrity, "artifact %s has no digest to verify against", ref.ID)
	}
	rc, err := s.Open(ref)
	if err != nil {
		return err
	}
	defer rc.Close()
	h := sha256.New()
	if _, err := io.Copy(h, rc); err != nil {
		return errs.Wrap(errs.CategoryInternal, err, "artifacts: verify %s", ref.ID)
	}
	got := "sha256:" + hex.EncodeToString(h.Sum(nil))
	if got != ref.Digest {
		return errs.New(errs.CategoryIntegrity,
			"artifact %s fails its digest check: stored %s, computed %s", ref.ID, ref.Digest, got)
	}
	return nil
}

// resolveLocator maps a locator produced by Put back to a filesystem path,
// refusing anything that does not stay under the store root (defence in
// depth against a future caller constructing a ref by hand rather than
// receiving one from Put).
func (s *Store) resolveLocator(locator string) (string, error) {
	projectID, digestHex, err := parseLocator(locator)
	if err != nil {
		return "", err
	}
	path := objectPath(s.root, projectID, digestHex)
	cleanRoot := filepath.Clean(s.root) + string(filepath.Separator)
	if !strings.HasPrefix(filepath.Clean(path)+string(filepath.Separator), cleanRoot) {
		return "", errs.New(errs.CategoryInvalidArgument, "artifacts: locator %q escapes the store root", locator)
	}
	return path, nil
}

func locatorFor(projectID, digestHex string) string {
	return fmt.Sprintf("artifact:%s:%s", projectID, digestHex)
}

func parseLocator(locator string) (projectID, digestHex string, err error) {
	parts := strings.SplitN(locator, ":", 3)
	if len(parts) != 3 || parts[0] != "artifact" {
		return "", "", errs.New(errs.CategoryInvalidArgument, "artifacts: malformed locator %q", locator)
	}
	if err := validateProjectID(parts[1]); err != nil {
		return "", "", err
	}
	if len(parts[2]) != 64 || !isHex(parts[2]) {
		return "", "", errs.New(errs.CategoryInvalidArgument, "artifacts: malformed locator %q", locator)
	}
	return parts[1], parts[2], nil
}

func isHex(s string) bool {
	for _, r := range s {
		if !((r >= '0' && r <= '9') || (r >= 'a' && r <= 'f')) {
			return false
		}
	}
	return true
}

func objectPath(root, projectID, digestHex string) string {
	return filepath.Join(root, projectID, "objects", digestHex[:2], digestHex)
}

// validateProjectID mirrors controlplane's project id policy so an artifact
// path component can never carry a path-traversal sequence or separator.
func validateProjectID(id string) error {
	if id == "" {
		return errs.New(errs.CategoryInvalidArgument, "artifacts: project id is required")
	}
	if len(id) > 64 {
		return errs.New(errs.CategoryInvalidArgument, "artifacts: project id too long")
	}
	for _, r := range id {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9', r == '-', r == '_':
		default:
			return errs.New(errs.CategoryInvalidArgument, "artifacts: project id %q has invalid characters", id)
		}
	}
	return nil
}
